[package]
name = "page-mon"
version = "0.1.0"
authors = ["owen <stensonowen@gmail.com>"]

build = "build.rs"

[build-dependencies]
lalrpop = "0.11.0"

[dependencies]
lalrpop-util = "0.11.0"
chrono = "0.2.22"
hyper = "0.9.10"
url = "1.1.1"
diff = "0.1.9"
select = "0.3.0"
lettre = "0.5.1"

